"""add campaign targeting tables

Revision ID: 1f5949987e3d
Revises: d51009978bca
Create Date: 2026-10-02 19:40:00.393817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5949987e3d'
down_revision: Union[str, Sequence[str], None] = 'd51009978bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_devices',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'device')
    )
    op.create_table('campaign_regions',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'region')
    )
    op.create_table('campaign_subscription_tiers',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'subscription_tier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_subscription_tiers')
    op.drop_table('campaign_regions')
    op.drop_table('campaign_devices')
    # ### end Alembic commands ###
